name: Build TWRP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev \
          gcc-multilib g++-multilib libc6-dev-i386 libncurses5 libncurses5-dev x11proto-core-dev \
          libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig python3 openjdk-11-jdk repo -y

    - name: Sync source
      run: |
        repo init -u https://github.com/minimal-manifest-twrp/platform_manifest_twrp_omni.git -b twrp-12.1
        repo sync -j$(nproc)

    - name: Clone device tree
      run: |
        git clone https://github.com/mototek/recovery_motorola_lima device/motorola/lima

    - name: Build TWRP
      run: |
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch omni_lima-eng
        mka bootimage

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: TWRP-Boot
        path: out/target/product/lima/boot.img
